GET localhost:3000/admin/update
Content-Type: application/json
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM0NjI2MDQ0LCJleHAiOjE3MzQ2NTQ4NDR9.a39xwI0H5WursGogY0HcamjufqCypincytVIBYm62z4
